USE SSG1_7
GO

-- Dept
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(1, 'ERP/BPM', '1')

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(2, 'EPM/HRMS', '2')

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(3, 'FSA/CRM', '3')

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(4, 'SYSTEM', '4')

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES(5, 'TECHNOLOGY', '5')
GO

-- Salgrade
INSERT INTO SALGRADE(GRADE, LOSAL, HISAL)
VALUES(1, 100, 25)

INSERT INTO SALGRADE(GRADE, LOSAL, HISAL)
VALUES(2, 200, 50)

INSERT INTO SALGRADE(GRADE, LOSAL, HISAL)
VALUES(3, 300, 75)

INSERT INTO SALGRADE(GRADE, LOSAL, HISAL)
VALUES(4, 400, 100)

INSERT INTO SALGRADE(GRADE, LOSAL, HISAL)
VALUES(5, 500, 125)
GO

-- Emp
INSERT INTO EMP(EMPNO, ENAME, JOB, HIREDATE, SAL, COMM, DEPTNO)
VALUES(1, N'Nguyễn', 'IT', GETDATE(), 100, 25, 1)

INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(2, N'Đình', 'Fresher', 1, GETDATE(), 200, 50, 1)

INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(3, N'Sang', 'CTO', 1, GETDATE(), 300, 75, 2)

INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(4, N'Đẹp', 'CEO', 2, GETDATE(), 400, 100, 2)

INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(5, N'Trai', 'HR', 2, GETDATE(), 500, 125, 3)

INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(6, N'Nhất', 'HR', 2, GETDATE(), 600, 150, 4)

INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
VALUES(7, N'May', 'CVG', 5, GETDATE(), 600, 5)
GO

-- Test
SELECT *
FROM DEPT

SELECT *
FROM SALGRADE

SELECT *
FROM EMP
GO